// export { cards };

const cards = [
  // {
  //   itype: 'Набор или открытка',
  //   name: 'Новый год',
  //   preview: 'set-2-ny-card-3-bear.jpg', // - картинка для галереи, лучшая
  //   images: ['set-2-ny-card-3-bear.jpg', 'set-2-ny-card-4-bear.jpg'],
  //   descr: 'Описание истории про медведя, как всё волшебно и хорошо выходит, не очень длинное но интересное',
  //   count: 5, // - количество предметов
  //   source: 'Матовая бумага 300г/м2', // ? везде же одинаковое
  //   format: 'A6' // ? и это тоже,  можно не указывать пока.
  // }
  {
    itype: 'Открытка',
    name: 'Кукузей',
    preview: 'gallery-cards-img-1-rooster-tale.jpg', 
    //images: ['',''],
    descr: 'История о Кукузее, райских птичках и большом сердце.',
    count: 1,
    price: '100',
  }, {
    itype: 'Открытка',
    name: 'Жуки',
    preview: 'gallery-cards-img-2-beatles-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Жуки"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Если успеть до темноты',
    preview: 'gallery-cards-img-3september.jpg', 
    //images: [''],
    descr: 'Настроение сентября',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Дружочки-грибочки',
    preview: 'gallery-cards-img-4-mushrooms-tale.jpg', 
    //images: [''],
    descr: 'Рецепт от осенней хмури',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Чай для друга',
    preview: 'gallery-cards-img-5-tea.jpg', 
    //images: [''],
    descr: 'А с чем он будет, допиши сам)',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Агашкин хвостик',
    preview: 'gallery-cards-img-6-agashka-tale.jpg', 
    //images: [''],
    descr: 'Про то, что все всегда налаживается, если по своей судьбе бежать.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Завари мне,осень,крепкий чай',
    preview: 'gallery-cards-img-7-tea-mushrooms.jpg', 
    //images: [''],
    descr: 'И постой тихонько у порога.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Твой путь',
    preview: 'gallery-cards-img-8-way-to-you.jpg', 
    //images: [''],
    descr: 'И чтобы начать его,вовсе не обязательно выходить из дома.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Волшебный шкаф',
    preview: 'gallery-cards-img-9-cupboard-tale.jpg', 
    //images: [''],
    descr: 'И то, к чему может привести обладание таким шкафом.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Лучший момент',
    preview: 'gallery-cards-img-10-crows.jpg', 
    //images: [''],
    descr: 'Который всегда случается неожиданно.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Лосиные думы',
    preview: 'gallery-cards-img-11-elk-tale.jpg', 
    //images: [''],
    descr: 'Диалог у ели о жизни и сне.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Агашка',
    preview: 'gallery-cards-img-12-agashka.jpg', 
    //images: [''],
    descr: 'Ящерица.Портрет',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Галаш',
    preview: 'gallery-cards-img-13-galash.jpg', 
    //images: [''],
    descr: 'Мотылек.Портрет',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Климент',
    preview: 'gallery-cards-img-14-kliment.jpg', 
    //images: [''],
    descr: 'Жук.Портрет.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Кузьма',
    preview: 'gallery-cards-img-15-kuzma.jpg', 
    //images: [''],
    descr: 'Ящер.Портрет.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Варун',
    preview: 'gallery-cards-img-16-varun.jpg', 
    //images: [''],
    descr: 'Жук.Портрет.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Лягух',
    preview: 'gallery-cards-img-17-liaguh.jpg', 
    //images: [''],
    descr: 'Лягушка.Портрет.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Жихан',
    preview: 'gallery-cards-img-18-zihan.jpg', 
    //images: [''],
    descr: 'Жук.Портрет.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Невзор',
    preview: 'gallery-cards-img-19-nevzor.jpg', 
    //images: [''],
    descr: 'Жук.Портрет.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Варгас',
    preview: 'gallery-cards-img-20-vargas.jpg', 
    //images: [''],
    descr: 'Жук.Портрет.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Сонный мак',
    preview: 'gallery-cards-img-21-poppy.jpg', 
    //images: [''],
    descr: 'В осенней стружке.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Октябрь',
    preview: 'gallery-cards-img-22-october.jpg', 
    //images: [''],
    descr: 'Через призму белки.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Птичка-синичка',
    preview: 'gallery-cards-img-23-tit.jpg', 
    //images: [''],
    descr: 'Мечта орнитолога.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Бык',
    preview: 'gallery-cards-img-24-bull.jpg', 
    //images: [''],
    descr: 'Священное животное в рождественском обрамлении.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Темная осень в полях',
    preview: 'gallery-cards-img-25-autumn-herbs-black-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Осень в полях.Темный."',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Запасы',
    preview: 'gallery-cards-img-26-cupboard-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Запасы"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Ночной летний луг',
    preview: 'gallery-cards-img-27-summer-herbs-black-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Ночной летний луг"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Райские птички',
    preview: 'gallery-cards-img-28-birds-black-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Райские птички"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Перидинеи светлые',
    preview: 'gallery-cards-img-29-sea-army-white-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Светлые Перидинеи"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Грибные истории',
    preview: 'gallery-cards-img-30-mushrooms-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Грибные истории"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Снежный город',
    preview: 'gallery-cards-img-31-snow-town.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Снежный город"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Светлая осень в полях',
    preview: 'gallery-cards-img-32-autumn-herbs-white-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Осень в полях.Светлый"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Советские игрушки.Темный',
    preview: 'gallery-cards-img-33-black-pattern-soviet.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Советские игрушки.Темный"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Мшистые сказки',
    preview: 'gallery-cards-img-34-lichens-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Мшистые сказки"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'В хлопковом мире киты зажигают звезды',
    preview: 'gallery-cards-img-35-cotton-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "В хлопковом мире киты зажигают звезды"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Перидинеи.Темные',
    preview: 'gallery-cards-img-36-sea-army-green-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Темные Перидинеи"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Замерзшие травы',
    preview: 'gallery-cards-img-37-winter-pink-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Замерзшие травы"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Советские игрушки.Светлый',
    preview: 'gallery-cards-img-38-white-pattern-soviet.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Советские игрушки.Светлый"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Летний луг',
    preview: 'gallery-cards-img-39-summer-herbs-white-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Летний луг"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Синичкины сказы',
    preview: 'gallery-cards-img-40-tits-pattern.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Синичкины сказы"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Дом в волшебном лесу',
    preview: 'gallery-cards-img-41-snow-house.jpg', 
    //images: [''],
    descr: 'Коллекционная открытка по мотивам авторского принта "Дом в волшебном лесу"',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Люди,как звезды',
    preview: 'gallery-cards-img-42-people-like-stars.jpg', 
    //images: [''],
    descr: 'Есть люди,как звезды. Есть люди,как песни.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Сядь в поезд',
    preview: 'gallery-cards-img-43-get-on-the-train.jpg', 
    //images: [''],
    descr: 'Сядь в поезд. Высадись у моря.',
    count: 1,
    price: '100',
  },{
    itype: 'Набор открыток',
    name: 'Советский',
    preview: 'gallery-cards-set-img-44-sovietnewyear.jpg', 
    //images: [''],
    descr: `Набор открыток по мотивам любимых Советских фильмов.
    В набор входят открытки:
    -Главное,чтобы костюмчик сидел.
    -Это я удачно зашел.
    -Товарищи!Есть установка.
    -Танцуют все!
    -Я требую продолжения банкета!`,
    count: 5,
    price: '450',
  },{
    itype: 'Открытка',
    name: 'Главное,чтобы костюмчик сидел',
    preview: 'gallery-cards-set-img-45-sovietnewyear-card-1-bear.jpg', 
    //images: [''],
    descr: 'Открытка по мотивам любимого Советского фильма.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Это я удачно зашел',
    preview: 'gallery-cards-set-img-46-sovietnewyear-card-2-squirrel.jpg', 
    //images: [''],
    descr: 'Открытка по мотивам любимого Советского фильма.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Товарищи!Есть установка.',
    preview: 'gallery-cards-set-img-47-sovietnewyear-card-3-mushroom.jpg', 
    //images: [''],
    descr: 'Весело встретить Новый год!',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Танцуют все!',
    preview: 'gallery-cards-set-img-48-sovietnewyear-card-4-hares.jpg', 
    //images: [''],
    descr: 'Открытка по мотивам любимого Советского фильма.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Я требую продолжения банкета.',
    preview: 'gallery-cards-set-img-49-sovietnewyear-card-5-fox.jpg', 
    //images: [''],
    descr: 'Открытка по мотивам любимого Советского фильма.',
    count: 1,
    price: '100',
  },{
    itype: 'Набор открыток',
    name: 'Зима в Сосновом углу',
    preview: 'galllery-cards-set-whitebears.jpg', 
    //images: [''],
    descr: `Набор открыток с настоящей снежной сказкой и новогодними пожеланиями внутри.
    В набор входят открытки:
    -Волшебный лес.
    -У нас есть мы.
    -Домик мастера.
    -Прочная радость.
    -Пусть в новом году!`,
    count: 5,
    price: '450',
  },{
    itype: 'Открытка',
    name: 'Волшебный лес',
    preview: 'set-whitebears-card-1-forest.jpg', 
    //images: [''],
    descr: 'Или о том, что будет,если идти вперед да вперед,не поднимая глаз.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'У нас есть мы',
    preview: 'set-whitebears-card-2-mother-son.jpg', 
    //images: [''],
    descr: 'Значит, и все остальное будет.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Домик мастера',
    preview: 'set-whitebears-card-3-window.jpg', 
    //images: [''],
    descr: 'Про мастерство и волшебство.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Прочная радость',
    preview: 'set-whitebears-card-4-help.jpg', 
    //images: [''],
    descr: 'От поистине волшебного предмета, который можно делить на сколько угодно друзей.',
    count: 1,
    price: '100',
  },{
    itype: 'Открытка',
    name: 'Пусть в Новом году!',
    preview: 'set-whitebears-card-5-happy-new-year.jpg', 
    //images: [''],
    descr: 'Со всеми добрыми пожеланиями для тебя, под каким бы небом ты ни был.',
    count: 1,
    price: '100',
  },
]